version: '3'

services:
  shc-postgres:
    image: postgres
    container_name: shc-postgres
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks: 
      - shc-network
  shc-api:
    build: 
      context: .
    image: shc-api
    env_file:
      - .env
    container_name: shc-api
    restart: always
    ports:
      - '3000:3000'
    networks: 
      - shc-network
    depends_on:
      - shc-postgres
volumes:
  postgres_data:

networks: 
  shc-network:
    name: shc-network
    driver: bridge
      